config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations],
             controllers: {
                 invitations: 'users/invitations'
             }
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    patch 'users/:id' => 'devise/registrations#update', :as => 'user_registration'
  end

    resources :courses do
    resources :chapters
    resources :student_grades, only: [:index, :update]
  end

  resources :messages, only: :index

  resources :comments

  namespace :admin do
    resources :users
    resources :study_years do
      resources :departments
    end
  end

  root to: "courses#index"

end

app/models/course.rb
class Course < ActiveRecord::Base

  acts_as_commentable

  belongs_to :department
  belongs_to :study_year

  has_many :course_teacher_memberships, dependent: :destroy
  has_many :teachers, through: :course_teacher_memberships, source: :teacher

  has_many :student_course_memberships, foreign_key: 'course_id'
  has_many :students, through: :student_course_memberships , source: :student

  has_many :chapters
  has_many :course_attachments, through: :chapters, source: :course_attachments

  has_many :student_grades

  def available_students
    User.where(role: 'student').where.not(id: study_year.students.where.not(id: self.students))
  end

  validates :title, presence: true, uniqueness: { scope: :study_year_id }
  validates :teacher_ids, length: { minimum: 1, :message => 'Select at least one teacher' }

end

app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :study_year

  has_many :courses, dependent: :destroy
  accepts_nested_attributes_for :courses, reject_if: :all_blank, allow_destroy: true

  def available_teachers
    User.where(role: 'prof')
  end

end

app/controllers/admin/departments_controller.rb
class Admin::DepartmentsController < AdminController

  before_action :load_study_year

  def index
    @departments = @study_year.departments
  end

  def new
    @department = @study_year.departments.build
    authorize! :create, @department
  end

  def edit
    @department = @study_year.departments.find(params[:id])
    authorize! :update, @department
  end

  def create
    @department = @study_year.departments.new(department_params)
    authorize! :create, @department
    if @department.save
      redirect_to admin_study_year_departments_path(@study_year.id), notice: 'Department was created'
    else
      render 'new'
    end
  end

  def update
    @department = @study_year.departments.find(params[:id])
    if @department.update(department_params)
      redirect_to admin_study_year_departments_path(@study_year.id), notice: 'Department was updated'
    else
      render 'edit'
    end
  end

  def destroy
    @department = @study_year.departments.find(params[:id])
    authorize! :delete, @department
    @department.destroy
    redirect_to admin_study_year_departments_path(@study_year.id), notice: 'Department was deleted'
  end

  private

  def department_params
    params.require(:department).permit(:name, courses_attributes: [:id, :title, :description, :_destroy, :study_year_id, student_ids: [], teacher_ids: []])
  end

  def load_study_year
    @study_year = StudyYear.find(params[:study_year_id])
    @available_students = User.students
  end

end

app/views/admin/departments/_course_fields.html.erb
<div class="form-group-row">
  <fieldset>
    <legend></legend>
  <div class="row">
    <div class="col-xs-3">
      <%= f.input :study_year_id, as: :hidden, input_html: { value: @study_year.id} %>
      <%= f.input :title, input_html: { placeholder: 'Course Name' }, label: false %>
    </div>

    <div class="col-xs-1">
      <%= link_to_remove_association '<i class="icm icm-bin"></i>'.html_safe, f, 'data-wrapper-class' => 'form-group-row' %>
    </div>

    <div class="col-xs-4">
      <%= f.input :teacher_ids,
                  as: :select,
                  collection: @department.available_teachers,
                  value_method: :id,
                  label_method: :to_label,
                  label: false,
                  input_html: {
                          multiple: true,
                          placeholder: 'Select Teachers'
                  }
      %>
    </div>

    <div class="col-xs-4">
      <%= f.input :student_ids,
                  as: :select,
                  collection: @available_students,
                  value_method: :id,
                  label_method: :to_label,
                  label: false,
                  input_html: {
                          multiple: true,
                          placeholder: 'Select Students'
                  }
      %>

    </div>
  </div>
    <div class="row">
      <div class="col-xs-12">
        <%= f.input :description %>
      </div>
    </div>
  </fieldset>
</div>

app/views/admin/departments/_course_teacher_membership_fields.html.erb
<div class="form-group-row">
  <div class="row">
    <div class="col-xs-10">
      <%= f.input :teacher_id,
                  as: :select,
                  include_blank: false,
                  label: false,
                  collection: @department.available_teachers,
                  value_method: :id,
                  label_method: :to_label
      %>
    </div>

    <div class="col-xs-1">
      <%= link_to_remove_association '<i class="icm icm-bin"></i>'.html_safe, f, 'data-wrapper-class' => 'form-group-row' %>
    </div>
  </div>

</div>

app/views/admin/departments/_form.html.erb
<%= simple_form_for [:admin, @study_year, @department] do |f| %>
    <%= f.input :name %>


    <div class="course-fields">
      <%= f.simple_fields_for :courses do |course| %>
          <%= render 'course_fields', f: course %>
      <% end %>
    </div>

    <%= link_to_add_association '<i class="icm icm-plus-circle"></i> <span>Add Course</span>'.html_safe, f, :courses,
                                partial: 'course_fields',
                                class: 'btn btn-success push-bottom',
                                'data-association-insertion-traversal' => 'siblings',
                                'data-association-insertion-node' => '.course-fields',
                                'data-association-insertion-method' => 'append',
                                'data-wrapper-class' => 'form-group-row' %>
    <fieldset>
      <legend></legend>

      <div class="form-actions">
        <%= f.button :submit %>
      </div>
    </fieldset>
<% end %>

app/views/admin/departments/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">Edit Department</div>
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/admin/departments/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      <div class="row">
        <div class="col-sm-6">
          Departments
        </div>
        <div class="col-sm-6 text-right">
          <%= link_to 'New Department', new_admin_study_year_department_path(@study_year), class: 'btn btn-success btn-sm' %>
        </div>
      </div>
    </div>
  </div>

  <div class="panel-body">
    <table class="table table-bordered table-striped" >
      <thead>
      <tr>
        <th>Name</th>
        <th>Options</th>
      </tr>
      </thead>
      <tbody>
      <% @departments.each do |department| %>
          <tr>
            <td><%= link_to department.name, edit_admin_study_year_department_path(@study_year, department) %></td>
            <td>
              <%= link_to admin_study_year_department_path(@study_year,department), method: :delete, data: {confirm: 'Are you sure?'}, title: 'Delete', rel: 'tooltip' do %>
                  <i class="icm icm-bin"></i>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/departments/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">Add Department</div>
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>