config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations],
             controllers: {
                 invitations: 'users/invitations'
             }
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    patch 'users/:id' => 'devise/registrations#update', :as => 'user_registration'
  end

    resources :courses do
    resources :chapters
    resources :student_grades, only: [:index, :update]
  end

  resources :messages, only: :index

  resources :comments

  namespace :admin do
    resources :users
    resources :study_years do
      resources :departments
    end
  end

  root to: "courses#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  ROLES = %w(admin prof student)

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # validates :name, presence: true

  has_many :student_course_memberships, foreign_key: 'student_id'
  has_many :participating_courses, class_name: 'Course', through: :student_course_memberships, source: :course

  has_many :course_teacher_memberships, foreign_key: 'teacher_id'
  has_many :teaching_courses, class_name: 'Course', through: :course_teacher_memberships, source: :course

  scope :students, -> { where(role: 'student') }

  has_many :student_grades, foreign_key: 'student_id'

  has_many :sent_messages, class_name: "Message", foreign_key: :sender_id, dependent: :destroy
  has_many :messages, class_name: "Message", foreign_key: :receiver_id, dependent: :destroy

  def admin?
    role == 'admin'
  end

  def my_courses
    if role == 'student'
      participating_courses
    elsif role == 'prof'
      teaching_courses
    elsif role == 'admin'
      Course.all
    end
  end

  def to_label
    "#{name} (#{email})"
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController

  #/users
  def index
    @users = User.all
  end

  #/users/new
  def new
    @user = User.new
  end

  #/users/:id/edit
  def edit
    @user = User.find(params[:id])
  end

  #POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path
    else
      render 'new'
    end
  end

  #PATCH /users/:id
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path
    else
      render 'edit'
    end

  end

  #DELETE /users/:id
  def destroy
    @user = User.find(params[:id])
    authorize! :destroy, @user
    @user.destroy
    redirect_to admin_users_path
  end

  private

  #strong params
  def user_params
    params.require(:user).permit(:name, :email, :role, :password, :password_confirmation)
  end
end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController

  before_filter :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:invite).concat [:name, :role]
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= simple_form_for [:admin, @user] do |f| %>
    <%= f.input :name %>
    <%= f.input :email %>
    <% unless @user.persisted? %>
        <%= f.input :password %>
        <%= f.input :password_confirmation %>
    <% end %>
    <%= f.input :role, as: :select, collection: User::ROLES, include_blank: false %>
    <%= f.button :submit %>
<% end %>

app/views/admin/users/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">Edit User</div>
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      <div class="row">
        <div class="col-sm-6">
          Users
        </div>
        <div class="col-sm-6 text-right">
          <%= link_to 'Invite', new_user_invitation_path, class: 'btn btn-primary btn-sm' %>
          <%= link_to 'New User', new_admin_user_path, class: 'btn btn-success btn-sm' %>
        </div>
      </div>
    </div>
  </div>

  <div class="panel-body">
    <table class="table table-bordered table-striped" >
      <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Role</th>
        <th>Options</th>
      </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= user.role %></td>
            <td>
              <%= link_to edit_admin_user_path(user), title: 'Edit', rel: 'tooltip' do %>
                  <i class="icm icm-pencil"></i>
              <% end %>

              <% if can?(:destroy, user) %>
                  <%= link_to admin_user_path(user), method: :delete, data: {confirm: 'Are you sure?'}, title: 'Delete', rel: 'tooltip' do %>
                      <i class="icm icm-bin"></i>
                  <% end %>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/users/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">Add User</div>
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>