config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations],
             controllers: {
                 invitations: 'users/invitations'
             }
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    patch 'users/:id' => 'devise/registrations#update', :as => 'user_registration'
  end

    resources :courses do
    resources :chapters
    resources :student_grades, only: [:index, :update]
  end

  resources :messages, only: :index

  resources :comments

  namespace :admin do
    resources :users
    resources :study_years do
      resources :departments
    end
  end

  root to: "courses#index"

end

app/models/study_year.rb
class StudyYear < ActiveRecord::Base

  has_many :departments, dependent: :destroy
  has_many :courses, through: :departments, source: :courses
  has_many :students, through: :courses, source: :students

end

app/controllers/admin/study_years_controller.rb
class Admin::StudyYearsController < AdminController

  def index
    @study_years = StudyYear.all
  end

  def new
    @study_year = StudyYear.new
    authorize! :create, @study_year
  end

  def edit
    @study_year = StudyYear.find(params[:id])
    authorize! :update, @study_year
  end

  def create
    @study_year = StudyYear.new(study_year_params)
    authorize! :create, @study_year
    if @study_year.save
      redirect_to new_admin_study_year_department_path(@study_year), notice: 'Study Year was created'
    else
      render 'new'
    end
  end

  def update
    @study_year = StudyYear.find(params[:id])
    if @study_year.update(study_year_params)
      redirect_to admin_study_years_path, notice: 'Study Year was updated'
    else
      render 'edit'
    end
  end

  def destroy
    @study_year = StudyYear.find(params[:id])
    authorize! :delete, @study_year
    @study_year.destroy
    redirect_to admin_study_years_path, notice: 'Study Year was deleted'
  end

  private

  def study_year_params
    params.require(:study_year).permit(:name, :start_date, departments_attributes: [:id, :name, :_destroy])
  end

end

app/views/admin/study_years/_form.html.erb
<%= simple_form_for [:admin, @study_year] do |f| %>
    <%= f.input :name %>
    <%= f.input :start_date %>


    <div class="form-actions">
      <%= f.button :submit %>
    </div>
<% end %>

app/views/admin/study_years/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">Edit Department</div>
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/admin/study_years/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      <div class="row">
        <div class="col-sm-6">
          Study Years
        </div>
        <div class="col-sm-6 text-right">
          <%= link_to 'New Study Year', new_admin_study_year_path, class: 'btn btn-success btn-sm' %>
        </div>
      </div>
    </div>
  </div>

  <div class="panel-body">
    <table class="table table-bordered table-striped" >
      <thead>
      <tr>
        <th>Name</th>
        <th>Options</th>
      </tr>
      </thead>
      <tbody>
      <% @study_years.each do |study_year| %>
          <tr>
            <td><%= link_to study_year.name, admin_study_year_departments_path(study_year) %></td>
            <td>
              <%= link_to edit_admin_study_year_path(study_year), title: 'Edit', rel: 'tooltip' do %>
                  <i class="icm icm-pencil"></i>
              <% end %>

              <%= link_to admin_study_year_path(study_year), method: :delete, data: {confirm: 'Are you sure?'}, title: 'Delete', rel: 'tooltip' do %>
                  <i class="icm icm-bin"></i>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/study_years/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">Add Study Year</div>
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>